# Generated by Django 4.0.5 on 2022-08-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='amount_of_times_read',
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReactToPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LI', 'Like'), ('LO', 'Love'), ('FU', 'Funny'), ('SA', 'Sad'), ('AN', 'Angry')], default='LI', max_length=2)),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacted_post', to='blog.post')),
                ('users', models.ManyToManyField(related_name='reacted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('post_read', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_read', to='blog.post')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PostsRead',
            },
        ),
    ]
