# Generated by Django 4.0.5 on 2022-08-04 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_rename_reacttopost_postreaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postread',
            options={'verbose_name_plural': 'Posts Read'},
        ),
        migrations.RemoveField(
            model_name='postreaction',
            name='users',
        ),
        migrations.AddField(
            model_name='postreaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacted_post', to='blog.post'),
        ),
    ]
