# Generated by Django 4.0.5 on 2022-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postread_options_remove_postreaction_users_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='post_user_unique'),
        ),
    ]
