# Generated by Django 4.0.5 on 2022-07-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='hi@mail.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
