# Generated by Django 4.0.5 on 2022-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(choices=[('EL', 'Email'), ('GE', 'Google')], default='EL', max_length=2),
        ),
    ]
